export const ARCHITECTURE_WORKFLOW = [
  "name: RalphWorks Architecture Review",
  "",
  "on:",
  "  workflow_dispatch:",
  "  schedule:",
  "    - cron: '0 2 * * 1'",
  "",
  "jobs:",
  "  review:",
  "    runs-on: ubuntu-latest",
  "    timeout-minutes: 40",
  "    permissions:",
  "      contents: read",
  "      issues: read",
  "    outputs:",
  "      skip: ${{ steps.backlog.outputs.skip }}",
  "    env:",
  "      GH_TOKEN: ${{ github.token }}",
  "      GH_REPO: ${{ github.repository }}",
  "      RALPHWORKS_MODEL: ${{ vars.RALPHWORKS_MODEL }}",
  "      RALPHWORKS_REF: ${{ vars.RALPHWORKS_REF || 'v0.1.0' }}",
  "      RALPHWORKS_SOURCE_REPO: ${{ vars.RALPHWORKS_SOURCE_REPO || 'OctopusGarage/ralphworks' }}",
  "    steps:",
  "      - name: Check backlog",
  "        id: backlog",
  "        run: |",
  "          set -euo pipefail",
  "          open=$(gh issue list --state open --label 'ralphworks:architecture' --limit 100 --json number --jq length)",
  "          [ \"$open\" -lt 3 ] || { echo 'Architecture backlog is full'; echo 'skip=true' >> \"$GITHUB_OUTPUT\"; }",
  "      - uses: actions/checkout@v4",
  "        if: steps.backlog.outputs.skip != 'true'",
  "        with:",
  "          persist-credentials: false",
  "      - uses: pnpm/action-setup@v4",
  "        if: steps.backlog.outputs.skip != 'true'",
  "        with:",
  "          version: 10.13.1",
  "      - uses: actions/setup-node@v4",
  "        if: steps.backlog.outputs.skip != 'true'",
  "        with:",
  "          node-version: 24",
  "      - name: Prepare review",
  "        if: steps.backlog.outputs.skip != 'true'",
  "        env:",
  "          SOURCE_TOKEN: ${{ secrets.RALPHWORKS_REPO_TOKEN }}",
  "        run: |",
  "          set -euo pipefail",
  '          [ -n "$RALPHWORKS_MODEL" ] || exit 1',
  '          if [ -n "$SOURCE_TOKEN" ]; then GH_TOKEN="$SOURCE_TOKEN" gh repo clone "$RALPHWORKS_SOURCE_REPO" "$RUNNER_TEMP/ralphworks"',
  '          else git clone "https://github.com/${RALPHWORKS_SOURCE_REPO}.git" "$RUNNER_TEMP/ralphworks"; fi',
  '          git -C "$RUNNER_TEMP/ralphworks" checkout --detach "$RALPHWORKS_REF"',
  '          pnpm --dir "$RUNNER_TEMP/ralphworks" install --frozen-lockfile',
  '          pnpm --dir "$RUNNER_TEMP/ralphworks" build',
  "          cat > \"$RUNNER_TEMP/architecture-task.md\" <<'TASK'",
  "          Inspect the repository architecture and identify one concrete, bounded improvement with evidence from current files. Write .ralph/architecture.md with a title on the first line and an actionable proposal with acceptance criteria. Do not change tracked project files. Signal DONE when complete.",
  "          TASK",
  "      - name: Run RalphWorks",
  "        if: steps.backlog.outputs.skip != 'true'",
  "        id: ralph",
  "        env:",
  "          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}",
  "          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}",
  "          NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}",
  "          ZAI_CODING_CN_API_KEY: ${{ secrets.ZAI_CODING_CN_API_KEY }}",
  "          RALPHWORKS_AUTH_SECRET_NAME: ${{ vars.RALPHWORKS_AUTH_SECRET }}",
  "          RALPHWORKS_AUTH_SECRET_VALUE: ${{ secrets[vars.RALPHWORKS_AUTH_SECRET] }}",
  "        run: |",
  "          set -euo pipefail",
  '          if [ -n "$RALPHWORKS_AUTH_SECRET_NAME" ]; then export "$RALPHWORKS_AUTH_SECRET_NAME=$RALPHWORKS_AUTH_SECRET_VALUE"; fi',
  '          node "$RUNNER_TEMP/ralphworks/dist/cli.js" run "$RUNNER_TEMP/architecture-task.md" --executor host --check \'test -s .ralph/architecture.md\' --max-iterations 3 --max-minutes 20 --max-cost-usd 1',
  "      - uses: actions/upload-artifact@v4",
  "        if: always() && steps.ralph.outcome != 'skipped'",
  "        with:",
  "          name: ralphworks-architecture",
  "          path: |",
  "            .ralph/architecture.md",
  "            .ralph/runs/",
  "          if-no-files-found: warn",
  "",
  "  publish:",
  "    needs: review",
  "    if: always() && needs.review.result == 'success' && needs.review.outputs.skip != 'true'",
  "    runs-on: ubuntu-latest",
  "    permissions:",
  "      issues: read",
  "      actions: read",
  "    env:",
  "      GH_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "      GH_REPO: ${{ github.repository }}",
  "    steps:",
  "      - uses: actions/download-artifact@v4",
  "        with:",
  "          name: ralphworks-architecture",
  "          path: ${{ runner.temp }}/architecture",
  "      - name: Publish proposal",
  "        run: |",
  "          set -euo pipefail",
  '          [ -n "$GH_TOKEN" ] || exit 1',
  '          result=$(find "$RUNNER_TEMP/architecture/runs" -name result.json -type f -print -quit)',
  '          jq -e \'.status == "completed"\' "$result" >/dev/null',
  '          file="$RUNNER_TEMP/architecture/architecture.md"',
  '          [ -s "$file" ] || exit 1',
  "          open=$(gh issue list --state open --label 'ralphworks:architecture' --limit 100 --json number --jq length)",
  '          [ "$open" -lt 3 ] || exit 0',
  "          title=$(head -n 1 \"$file\" | sed 's/^# *//')",
  '          [ -n "$title" ] || exit 1',
  '          gh issue create --title "Architecture: ${title:0:220}" --body-file "$file" --label \'ralphworks:architecture\'',
  "",
].join("\n");
