import { PROVIDER_CREDENTIAL_ENV, RALPHWORKS_CHECKOUT_AND_BUILD } from "./workflow-execution.ts";

export const ARCHITECTURE_WORKFLOW = [
  "name: RalphWorks Architecture Review",
  "",
  "on:",
  "  workflow_dispatch:",
  "  schedule:",
  "    - cron: '0 2 * * 1'",
  "",
  "jobs:",
  "  review:",
  "    runs-on: ubuntu-latest",
  "    concurrency:",
  "      group: ralphworks-architecture-${{ github.repository }}",
  "      cancel-in-progress: false",
  "    timeout-minutes: 40",
  "    permissions:",
  "      contents: read",
  "      issues: read",
  "    outputs:",
  "      skip: ${{ steps.backlog.outputs.skip }}",
  "    env:",
  "      GH_TOKEN: ${{ github.token }}",
  "      GH_REPO: ${{ github.repository }}",
  "      RALPHWORKS_MODEL: ${{ vars.RALPHWORKS_MODEL }}",
  "      RALPHWORKS_ARCHITECTURE_SKILL_REF: ${{ vars.RALPHWORKS_ARCHITECTURE_SKILL_REF }}",
  "      RALPHWORKS_REF: ${{ vars.RALPHWORKS_REF || 'v0.1.1' }}",
  "      RALPHWORKS_SOURCE_REPO: ${{ vars.RALPHWORKS_SOURCE_REPO || 'OctopusGarage/ralphworks' }}",
  "    steps:",
  "      - name: Check backlog",
  "        id: backlog",
  "        run: |",
  "          set -euo pipefail",
  "          open=$(gh issue list --state open --label 'ralphworks:architecture' --limit 100 --json number --jq length)",
  "          [ \"$open\" -lt 3 ] || { echo 'Architecture backlog is full'; echo 'skip=true' >> \"$GITHUB_OUTPUT\"; }",
  "      - uses: actions/checkout@v4",
  "        if: steps.backlog.outputs.skip != 'true'",
  "        with:",
  "          persist-credentials: false",
  "      - uses: pnpm/action-setup@v4",
  "        if: steps.backlog.outputs.skip != 'true'",
  "        with:",
  "          version: 10.13.1",
  "      - uses: actions/setup-node@v4",
  "        if: steps.backlog.outputs.skip != 'true'",
  "        with:",
  "          node-version: 24",
  "      - name: Prepare review",
  "        if: steps.backlog.outputs.skip != 'true'",
  "        env:",
  "          SOURCE_TOKEN: ${{ secrets.RALPHWORKS_REPO_TOKEN }}",
  "        run: |",
  "          set -euo pipefail",
  '          [ -n "$RALPHWORKS_MODEL" ] || exit 1',
  ...RALPHWORKS_CHECKOUT_AND_BUILD,
  '          if [ -n "$RALPHWORKS_ARCHITECTURE_SKILL_REF" ]; then',
  '            git clone https://github.com/mattpocock/skills.git "$RUNNER_TEMP/matt-skills"',
  '            git -C "$RUNNER_TEMP/matt-skills" checkout --detach "$RALPHWORKS_ARCHITECTURE_SKILL_REF"',
  '            skill="$RUNNER_TEMP/matt-skills/skills/engineering/improve-codebase-architecture"',
  '            vocabulary="$RUNNER_TEMP/matt-skills/skills/engineering/codebase-design"',
  '            test -s "$skill/SKILL.md" && test -s "$skill/HTML-REPORT.md" && test -s "$vocabulary/SKILL.md"',
  '            mkdir -p "$HOME/.pi/agent/skills" .ralph',
  '            cp -R "$skill" "$vocabulary" "$HOME/.pi/agent/skills/"',
  '            printf "mattpocock/skills@%s\\n" "$(git -C "$RUNNER_TEMP/matt-skills" rev-parse HEAD)" > .ralph/skill-source.txt',
  "          fi",
  '          if [ -n "$RALPHWORKS_ARCHITECTURE_SKILL_REF" ]; then',
  "            cat > \"$RUNNER_TEMP/architecture-task.md\" <<'TASK'",
  "          Read ~/.pi/agent/skills/improve-codebase-architecture/SKILL.md and its codebase-design vocabulary. Run the exploration and report stages for this repository. This is an unattended survey: do not invoke interactive grilling, subagents, or a host Skill tool. Write .ralph/architecture.html as the visual report and .ralph/architecture.md as a concise, evidence-backed proposal with a title on the first line and acceptance criteria. Use local copies of referenced skill files. Do not open a browser. Do not change tracked project files. Signal DONE only when both files exist and are complete.",
  "          TASK",
  "          else",
  "          cat > \"$RUNNER_TEMP/architecture-task.md\" <<'TASK'",
  "          Inspect the repository architecture and identify one concrete, bounded improvement with evidence from current files. Write .ralph/architecture.md with a title on the first line and an actionable proposal with acceptance criteria. Do not change tracked project files. Signal DONE when complete.",
  "          TASK",
  "          fi",
  "      - name: Run RalphWorks",
  "        if: steps.backlog.outputs.skip != 'true'",
  "        id: ralph",
  "        env:",
  ...PROVIDER_CREDENTIAL_ENV,
  "        run: |",
  "          set -euo pipefail",
  '          if [ -n "$RALPHWORKS_AUTH_SECRET_NAME" ]; then export "$RALPHWORKS_AUTH_SECRET_NAME=$RALPHWORKS_AUTH_SECRET_VALUE"; fi',
  '          if [ -n "$RALPHWORKS_ARCHITECTURE_SKILL_REF" ]; then check="test -s .ralph/architecture.md && test -s .ralph/architecture.html"; else check="test -s .ralph/architecture.md"; fi',
  '          node "$RUNNER_TEMP/ralphworks/dist/cli.js" run "$RUNNER_TEMP/architecture-task.md" --executor host --check "$check" --max-iterations 3 --max-minutes 20 --max-cost-usd 1',
  "      - uses: actions/upload-artifact@v4",
  "        if: always() && steps.ralph.outcome != 'skipped'",
  "        with:",
  "          name: ralphworks-architecture",
  "          path: |",
  "            .ralph/architecture.md",
  "            .ralph/architecture.html",
  "            .ralph/skill-source.txt",
  "            .ralph/runs/",
  "          if-no-files-found: warn",
  "",
  "  publish:",
  "    needs: review",
  "    if: always() && needs.review.result == 'success' && needs.review.outputs.skip != 'true'",
  "    runs-on: ubuntu-latest",
  "    permissions:",
  "      issues: read",
  "      actions: read",
  "    env:",
  "      GH_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "      GH_REPO: ${{ github.repository }}",
  "    steps:",
  "      - uses: actions/download-artifact@v4",
  "        with:",
  "          name: ralphworks-architecture",
  "          path: ${{ runner.temp }}/architecture",
  "      - name: Publish proposal",
  "        run: |",
  "          set -euo pipefail",
  '          [ -n "$GH_TOKEN" ] || exit 1',
  '          result=$(find "$RUNNER_TEMP/architecture/runs" -name result.json -type f -print -quit)',
  '          jq -e \'.status == "completed"\' "$result" >/dev/null',
  '          file="$RUNNER_TEMP/architecture/architecture.md"',
  '          [ -s "$file" ] || exit 1',
  "          open=$(gh issue list --state open --label 'ralphworks:architecture' --limit 100 --json number --jq length)",
  '          [ "$open" -lt 3 ] || exit 0',
  "          title=$(head -n 1 \"$file\" | sed 's/^# *//')",
  '          [ -n "$title" ] || exit 1',
  '          source_file="$RUNNER_TEMP/architecture/skill-source.txt"',
  '          if [ -s "$source_file" ]; then printf "\\nSkill source: %s\\n" "$(cat "$source_file")" >> "$file"; fi',
  '          printf "\\n[Run and report artifact](%s)\\n" "https://github.com/$GH_REPO/actions/runs/$GITHUB_RUN_ID" >> "$file"',
  '          gh issue create --title "Architecture: ${title:0:220}" --body-file "$file" --label \'ralphworks:architecture\'',
  "",
].join("\n");
