export const ISSUE_WORKFLOW = [
  "name: RalphWorks Issue",
  "",
  "on:",
  "  issues:",
  "    types: [labeled]",
  "",
  "concurrency:",
  "  group: ralphworks-issue-${{ github.event.issue.number }}",
  "  cancel-in-progress: false",
  "",
  "jobs:",
  "  run:",
  "    if: github.event.label.name == 'ralphworks:run' && github.event.issue.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    timeout-minutes: 60",
  "    permissions:",
  "      contents: read",
  "      issues: read",
  "    env:",
  "      GH_TOKEN: ${{ github.token }}",
  "      GH_REPO: ${{ github.repository }}",
  "      ISSUE_NUMBER: ${{ github.event.issue.number }}",
  "      LABEL_ACTOR: ${{ github.event.sender.login }}",
  "      RALPHWORKS_MODEL: ${{ vars.RALPHWORKS_MODEL }}",
  "      RALPHWORKS_CHECK: ${{ vars.RALPHWORKS_ISSUE_CHECK }}",
  "      RALPHWORKS_REF: ${{ vars.RALPHWORKS_REF || 'v0.1.0' }}",
  "      RALPHWORKS_SOURCE_REPO: ${{ vars.RALPHWORKS_SOURCE_REPO || 'OctopusGarage/ralphworks' }}",
  "    steps:",
  "      - name: Authorize trigger and check configuration",
  "        env:",
  "          ISSUE_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "        run: |",
  "          set -euo pipefail",
  '          permission=$(gh api "repos/$GITHUB_REPOSITORY/collaborators/$LABEL_ACTOR/permission" --jq .permission)',
  '          case "$permission" in admin|maintain|write) ;; *) echo "Label actor lacks write access" >&2; exit 1;; esac',
  '          [ -n "$RALPHWORKS_MODEL" ] || { echo "RALPHWORKS_MODEL is required" >&2; exit 1; }',
  '          [ -n "$RALPHWORKS_CHECK" ] || { echo "RALPHWORKS_ISSUE_CHECK is required" >&2; exit 1; }',
  '          [ -n "$ISSUE_TOKEN" ] || { echo "RALPHWORKS_ISSUE_TOKEN is required" >&2; exit 1; }',
  '          existing=$(gh pr list --state open --search "in:body \\"Closes #${ISSUE_NUMBER}\\"" --json number,body --jq "[.[] | select(.body | contains(\\"Closes #${ISSUE_NUMBER}\\"))] | length")',
  '          [ "$existing" = 0 ] || { echo "An open PR already closes this issue" >&2; exit 1; }',
  '          if gh api "repos/$GITHUB_REPOSITORY/branches/ralphworks/issue-$ISSUE_NUMBER" --jq .name >/dev/null 2>&1; then',
  '            echo "Issue branch already exists; inspect it before retrying" >&2',
  "            exit 1",
  "          fi",
  "      - uses: actions/checkout@v4",
  "        with:",
  "          persist-credentials: false",
  "      - uses: pnpm/action-setup@v4",
  "        with:",
  "          version: 10.13.1",
  "      - uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 24",
  "      - name: Checkout and build RalphWorks",
  "        env:",
  "          SOURCE_TOKEN: ${{ secrets.RALPHWORKS_REPO_TOKEN }}",
  "        run: |",
  "          set -euo pipefail",
  '          [[ "$RALPHWORKS_SOURCE_REPO" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || exit 1',
  '          if [ -n "$SOURCE_TOKEN" ]; then',
  '            GH_TOKEN="$SOURCE_TOKEN" gh repo clone "$RALPHWORKS_SOURCE_REPO" "$RUNNER_TEMP/ralphworks"',
  "          else",
  '            git clone "https://github.com/${RALPHWORKS_SOURCE_REPO}.git" "$RUNNER_TEMP/ralphworks"',
  "          fi",
  '          git -C "$RUNNER_TEMP/ralphworks" checkout --detach "$RALPHWORKS_REF"',
  '          pnpm --dir "$RUNNER_TEMP/ralphworks" install --frozen-lockfile',
  '          pnpm --dir "$RUNNER_TEMP/ralphworks" build',
  "      - name: Prepare issue task and dependencies",
  "        env:",
  "          ISSUE_TITLE: ${{ github.event.issue.title }}",
  "          ISSUE_BODY: ${{ github.event.issue.body }}",
  "        run: |",
  "          set -euo pipefail",
  '          printf \'# Issue #%s: %s\\n\\n%s\\n\' "$ISSUE_NUMBER" "$ISSUE_TITLE" "$ISSUE_BODY" > "$RUNNER_TEMP/issue-task.md"',
  "          if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile",
  "          elif [ -f package-lock.json ]; then npm ci",
  "          elif [ -f yarn.lock ]; then yarn install --frozen-lockfile",
  "          fi",
  '          echo "RALPH_BASE=$(git rev-parse HEAD)" >> "$GITHUB_ENV"',
  "      - name: Run RalphWorks",
  "        id: ralph",
  "        env:",
  "          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}",
  "          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}",
  "          NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}",
  "          ZAI_CODING_CN_API_KEY: ${{ secrets.ZAI_CODING_CN_API_KEY }}",
  "          RALPHWORKS_AUTH_SECRET_NAME: ${{ vars.RALPHWORKS_AUTH_SECRET }}",
  "          RALPHWORKS_AUTH_SECRET_VALUE: ${{ secrets[vars.RALPHWORKS_AUTH_SECRET] }}",
  "        run: |",
  "          set -euo pipefail",
  '          if [ -n "$RALPHWORKS_AUTH_SECRET_NAME" ]; then',
  '            [[ "$RALPHWORKS_AUTH_SECRET_NAME" =~ ^[A-Z][A-Z0-9_]*$ ]] || exit 1',
  '            [ -n "$RALPHWORKS_AUTH_SECRET_VALUE" ] || exit 1',
  '            export "$RALPHWORKS_AUTH_SECRET_NAME=$RALPHWORKS_AUTH_SECRET_VALUE"',
  "          fi",
  "          set +e",
  '          node "$RUNNER_TEMP/ralphworks/dist/cli.js" run "$RUNNER_TEMP/issue-task.md" --executor host --check "$RALPHWORKS_CHECK" --max-iterations 5 --max-minutes 30 --max-cost-usd 3',
  "          status=$?",
  "          set -e",
  '          echo "exit_code=$status" >> "$GITHUB_OUTPUT"',
  "      - name: Export run result and patch",
  "        if: always() && steps.ralph.outcome != 'skipped'",
  "        run: |",
  "          mkdir -p .ralph/export",
  "          git add -N --all",
  "          git diff --binary \"${RALPH_BASE:-HEAD}\" -- . ':!.ralph' > .ralph/export/change.patch",
  '          git rev-parse "${RALPH_BASE:-HEAD}" > .ralph/export/base-sha.txt',
  "      - uses: actions/upload-artifact@v4",
  "        if: always() && steps.ralph.outcome != 'skipped'",
  "        with:",
  "          name: ralphworks-issue-result",
  "          path: |",
  "            .ralph/export/",
  "            .ralph/runs/",
  "            .ralph/progress/",
  "          if-no-files-found: error",
  "",
  "  deliver:",
  "    needs: run",
  "    if: always() && github.event.label.name == 'ralphworks:run' && github.event.issue.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    timeout-minutes: 10",
  "    permissions:",
  "      contents: read",
  "      issues: read",
  "      actions: read",
  "    env:",
  "      GH_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "      GH_REPO: ${{ github.repository }}",
  "      ISSUE_NUMBER: ${{ github.event.issue.number }}",
  "      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
  "      BRANCH: ralphworks/issue-${{ github.event.issue.number }}",
  "    steps:",
  "      - name: Verify execution and download artifact",
  "        run: |",
  "          set -euo pipefail",
  '          [ "${{ needs.run.result }}" = success ] || { echo "Execution job failed" >&2; exit 1; }',
  '          [ -n "$GH_TOKEN" ] || { echo "RALPHWORKS_ISSUE_TOKEN is required" >&2; exit 1; }',
  "      - uses: actions/download-artifact@v4",
  "        with:",
  "          name: ralphworks-issue-result",
  "          path: ${{ runner.temp }}/ralph-result",
  "      - name: Validate completed result",
  "        run: |",
  "          set -euo pipefail",
  '          result=$(find "$RUNNER_TEMP/ralph-result/runs" -name result.json -type f -print -quit)',
  '          [ -n "$result" ] || { echo "Missing RalphWorks result" >&2; exit 1; }',
  '          jq -e \'.status == "completed" and (.iterations as $last | [.checks[] | select(.iteration == $last)] | length > 0) and (.iterations as $last | [.checks[] | select(.iteration == $last and .exitCode != 0)] | length == 0)\' "$result" >/dev/null',
  '          [ -s "$RUNNER_TEMP/ralph-result/export/change.patch" ] || { echo "Completed task produced no patch" >&2; exit 1; }',
  "      - uses: actions/checkout@v4",
  "        with:",
  "          persist-credentials: false",
  "          fetch-depth: 0",
  "      - name: Apply patch and open draft PR",
  "        id: pr",
  "        env:",
  "          ISSUE_TITLE: ${{ github.event.issue.title }}",
  "        run: |",
  "          set -euo pipefail",
  '          base=$(cat "$RUNNER_TEMP/ralph-result/export/base-sha.txt")',
  '          [ "$(git rev-parse HEAD)" = "$base" ] || { echo "Default branch changed during execution" >&2; exit 1; }',
  '          if gh api "repos/$GITHUB_REPOSITORY/branches/$BRANCH" --jq .name >/dev/null 2>&1; then',
  '            echo "Issue branch already exists" >&2',
  "            exit 1",
  "          fi",
  '          git switch -c "$BRANCH"',
  '          git apply --check "$RUNNER_TEMP/ralph-result/export/change.patch"',
  '          git apply "$RUNNER_TEMP/ralph-result/export/change.patch"',
  "          git config user.name 'ralphworks[bot]'",
  "          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'",
  "          git add -A",
  '          git commit -m "fix: address issue #$ISSUE_NUMBER"',
  "          auth=$(printf 'x-access-token:%s' \"$GH_TOKEN\" | base64 | tr -d '\\n')",
  '          git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $auth" push origin "HEAD:refs/heads/$BRANCH"',
  '          printf \'Closes #%s\\n\\nGenerated by RalphWorks. [Execution and artifacts](%s). Review the patch and required checks before merging.\\n\' "$ISSUE_NUMBER" "$RUN_URL" > "$RUNNER_TEMP/pr-body.md"',
  "          title=\"Fix #$ISSUE_NUMBER: ${ISSUE_TITLE//$'\\n'/ }\"",
  '          pr_url=$(gh pr create --draft --base "${{ github.event.repository.default_branch }}" --head "$BRANCH" --title "${title:0:256}" --body-file "$RUNNER_TEMP/pr-body.md")',
  '          gh pr edit "$pr_url" --add-label "ralphworks:review"',
  '          echo "url=$pr_url" >> "$GITHUB_OUTPUT"',
  "      - name: Update issue on success",
  "        if: success()",
  "        env:",
  "          PR_URL: ${{ steps.pr.outputs.url }}",
  "        run: |",
  "          gh issue edit \"$ISSUE_NUMBER\" --remove-label 'ralphworks:run' || true",
  '          gh issue comment "$ISSUE_NUMBER" --body "RalphWorks created draft PR $PR_URL. Run and artifacts: $RUN_URL"',
  "      - name: Report failure on issue",
  "        if: failure() && env.GH_TOKEN != ''",
  "        run: |",
  "          gh issue edit \"$ISSUE_NUMBER\" --remove-label 'ralphworks:run' || true",
  '          gh issue comment "$ISSUE_NUMBER" --body "RalphWorks could not create a PR. Inspect the [run and artifacts]($RUN_URL), resolve the cause, then re-add the \\`ralphworks:run\\` label to retry."',
  "",
].join("\n");
