import { failureComment, PROVIDER_CREDENTIAL_ENV, RALPHWORKS_CHECKOUT_AND_BUILD } from "./workflow-execution.ts";

export const PR_FEEDBACK_WORKFLOW = [
  "name: RalphWorks PR Feedback",
  "",
  "on:",
  "  pull_request_target:",
  "    types: [labeled]",
  "",
  "concurrency:",
  "  group: ralphworks-feedback-${{ github.event.pull_request.number }}",
  "  cancel-in-progress: false",
  "",
  "jobs:",
  "  implement:",
  "    if: github.event.label.name == 'ralphworks:implement' && github.event.pull_request.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    timeout-minutes: 60",
  "    permissions:",
  "      contents: read",
  "      pull-requests: read",
  "    env:",
  "      GH_TOKEN: ${{ github.token }}",
  "      GH_REPO: ${{ github.repository }}",
  "      PR_NUMBER: ${{ github.event.pull_request.number }}",
  "      LABEL_ACTOR: ${{ github.event.sender.login }}",
  "      HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}",
  "      HEAD_SHA: ${{ github.event.pull_request.head.sha }}",
  "      BASE_REF: ${{ github.event.pull_request.base.ref }}",
  "      RALPHWORKS_MODEL: ${{ vars.RALPHWORKS_MODEL }}",
  "      RALPHWORKS_CHECK: ${{ vars.RALPHWORKS_ISSUE_CHECK }}",
  "      RALPHWORKS_REF: ${{ vars.RALPHWORKS_REF || 'v0.1.1' }}",
  "      RALPHWORKS_SOURCE_REPO: ${{ vars.RALPHWORKS_SOURCE_REPO || 'OctopusGarage/ralphworks' }}",
  "    steps:",
  "      - name: Authorize feedback run",
  "        run: |",
  "          set -euo pipefail",
  '          [ "$HEAD_REPO" = "$GITHUB_REPOSITORY" ] || { echo \'Fork PRs are not supported\' >&2; exit 1; }',
  '          permission=$(gh api "repos/$GITHUB_REPOSITORY/collaborators/$LABEL_ACTOR/permission" --jq .permission)',
  "          case \"$permission\" in admin|write) ;; *) echo 'Label actor lacks write access' >&2; exit 1;; esac",
  '          [ -n "$RALPHWORKS_MODEL" ] && [ -n "$RALPHWORKS_CHECK" ] || exit 1',
  '          gh api "repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" --jq \'[.[] | .body] | join("\\n\\n")\' > "$RUNNER_TEMP/comments.txt"',
  '          gh api "repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" --jq \'[.[] | select(.body != null) | .body] | join("\\n\\n")\' >> "$RUNNER_TEMP/comments.txt"',
  "          [ -s \"$RUNNER_TEMP/comments.txt\" ] || { echo 'No PR feedback exists' >&2; exit 1; }",
  "      - uses: actions/checkout@v4",
  "        with:",
  "          ref: ${{ github.event.pull_request.head.sha }}",
  "          persist-credentials: false",
  "          fetch-depth: 0",
  "      - uses: pnpm/action-setup@v4",
  "        with:",
  "          version: 10.13.1",
  "      - uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 24",
  "      - name: Prepare task and dependencies",
  "        env:",
  "          SOURCE_TOKEN: ${{ secrets.RALPHWORKS_REPO_TOKEN }}",
  "        run: |",
  "          set -euo pipefail",
  ...RALPHWORKS_CHECKOUT_AND_BUILD,
  "          if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile",
  "          elif [ -f package-lock.json ]; then npm ci",
  "          elif [ -f yarn.lock ]; then yarn install --frozen-lockfile",
  "          fi",
  "          cat > \"$RUNNER_TEMP/feedback-task.md\" <<'TASK'",
  "          Address the actionable review feedback on this pull request. Inspect the current branch and the comments file below. Make the needed code and test changes, run the configured checks, and signal DONE. Do not commit or change Git HEAD.",
  "          TASK",
  '          printf \'\\nPR feedback file: %s\\n\' "$RUNNER_TEMP/comments.txt" >> "$RUNNER_TEMP/feedback-task.md"',
  "      - name: Run RalphWorks",
  "        id: ralph",
  "        env:",
  ...PROVIDER_CREDENTIAL_ENV,
  "        run: |",
  "          set -euo pipefail",
  '          if [ -n "$RALPHWORKS_AUTH_SECRET_NAME" ]; then export "$RALPHWORKS_AUTH_SECRET_NAME=$RALPHWORKS_AUTH_SECRET_VALUE"; fi',
  '          node "$RUNNER_TEMP/ralphworks/dist/cli.js" run "$RUNNER_TEMP/feedback-task.md" --executor host --check "$RALPHWORKS_CHECK" --max-iterations 5 --max-minutes 30 --max-cost-usd 3',
  "      - name: Export patch",
  "        if: always() && steps.ralph.outcome != 'skipped'",
  "        run: |",
  "          mkdir -p .ralph/export",
  "          git add -N --all",
  "          git diff --binary \"$HEAD_SHA\" -- . ':!.ralph' > .ralph/export/change.patch",
  "          printf '%s\\n' \"$HEAD_SHA\" > .ralph/export/base-sha.txt",
  "      - uses: actions/upload-artifact@v4",
  "        if: always() && steps.ralph.outcome != 'skipped'",
  "        with:",
  "          name: ralphworks-feedback",
  "          path: |",
  "            .ralph/export/",
  "            .ralph/runs/",
  "          if-no-files-found: warn",
  "",
  "  deliver:",
  "    needs: implement",
  "    if: always() && github.event.label.name == 'ralphworks:implement' && github.event.pull_request.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    permissions:",
  "      contents: read",
  "      pull-requests: read",
  "      actions: read",
  "    env:",
  "      GH_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "      GH_REPO: ${{ github.repository }}",
  "      PR_NUMBER: ${{ github.event.pull_request.number }}",
  "      BRANCH: ${{ github.event.pull_request.head.ref }}",
  "      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
  "    steps:",
  "      - name: Require completed run",
  "        run: |",
  '          [ "${{ needs.implement.result }}" = success ] || exit 1',
  '          [ -n "$GH_TOKEN" ] || exit 1',
  "      - uses: actions/download-artifact@v4",
  "        with:",
  "          name: ralphworks-feedback",
  "          path: ${{ runner.temp }}/feedback",
  "      - name: Validate result",
  "        run: |",
  "          set -euo pipefail",
  '          result=$(find "$RUNNER_TEMP/feedback/runs" -name result.json -type f -print -quit)',
  '          [ -n "$result" ] || exit 1',
  '          jq -e \'.status == "completed" and (.iterations as $last | [.checks[] | select(.iteration == $last)] | length > 0) and (.iterations as $last | [.checks[] | select(.iteration == $last and .exitCode != 0)] | length == 0)\' "$result" >/dev/null',
  '          [ -s "$RUNNER_TEMP/feedback/export/change.patch" ] || exit 1',
  "      - uses: actions/checkout@v4",
  "        with:",
  "          ref: ${{ github.event.pull_request.head.sha }}",
  "          persist-credentials: false",
  "          fetch-depth: 0",
  "      - name: Apply patch and push",
  "        run: |",
  "          set -euo pipefail",
  '          current=$(gh pr view "$PR_NUMBER" --json headRefOid --jq .headRefOid)',
  '          base=$(cat "$RUNNER_TEMP/feedback/export/base-sha.txt")',
  '          if [ "$current" != "$base" ] || [ "$(git rev-parse HEAD)" != "$base" ]; then echo \'PR branch advanced\' >&2; exit 1; fi',
  '          git switch -c "$BRANCH"',
  '          git apply --check "$RUNNER_TEMP/feedback/export/change.patch"',
  '          git apply "$RUNNER_TEMP/feedback/export/change.patch"',
  "          git config user.name 'ralphworks[bot]'",
  "          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'",
  "          git add -A",
  '          git commit -m "fix: address PR #$PR_NUMBER feedback"',
  "          auth=$(printf 'x-access-token:%s' \"$GH_TOKEN\" | base64 | tr -d '\\n')",
  '          git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $auth" push origin "HEAD:refs/heads/$BRANCH"',
  "          gh pr edit \"$PR_NUMBER\" --remove-label 'ralphworks:implement' || true",
  "          gh pr edit \"$PR_NUMBER\" --remove-label 'ralphworks:blocked' || true",
  '          gh pr comment "$PR_NUMBER" --body "RalphWorks addressed PR feedback in $(git rev-parse --short HEAD). Run: $RUN_URL"',
  "      - name: Report failure",
  "        if: failure() && env.GH_TOKEN != ''",
  "        run: |",
  "          gh pr edit \"$PR_NUMBER\" --remove-label 'ralphworks:implement' || true",
  "          gh pr edit \"$PR_NUMBER\" --add-label 'ralphworks:blocked' || true",
  ...failureComment(
    "ralphworks-feedback",
    "PR_NUMBER",
    "ralphworks:implement",
    "RalphWorks feedback run failed. Inspect the run, then re-add ralphworks:implement to retry.",
    "pr",
  ),
  "",
].join("\n");
