import { PROVIDER_CREDENTIAL_ENV, RALPHWORKS_CHECKOUT_AND_BUILD } from "./workflow-execution.ts";

export const PR_REVIEW_WORKFLOW = [
  "name: RalphWorks PR Review",
  "",
  "on:",
  "  pull_request_target:",
  "    types: [labeled]",
  "",
  "concurrency:",
  "  group: ralphworks-review-${{ github.event.pull_request.number }}",
  "  cancel-in-progress: false",
  "",
  "jobs:",
  "  review:",
  "    if: github.event.label.name == 'ralphworks:review' && github.event.pull_request.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    timeout-minutes: 40",
  "    permissions:",
  "      contents: read",
  "      pull-requests: read",
  "    env:",
  "      GH_TOKEN: ${{ github.token }}",
  "      GH_REPO: ${{ github.repository }}",
  "      PR_NUMBER: ${{ github.event.pull_request.number }}",
  "      LABEL_ACTOR: ${{ github.event.sender.login }}",
  "      HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}",
  "      HEAD_SHA: ${{ github.event.pull_request.head.sha }}",
  "      BASE_REF: ${{ github.event.pull_request.base.ref }}",
  "      RALPHWORKS_MODEL: ${{ vars.RALPHWORKS_MODEL }}",
  "      RALPHWORKS_REF: ${{ vars.RALPHWORKS_REF || 'v0.1.1' }}",
  "      RALPHWORKS_SOURCE_REPO: ${{ vars.RALPHWORKS_SOURCE_REPO || 'OctopusGarage/ralphworks' }}",
  "    steps:",
  "      - name: Authorize review",
  "        run: |",
  "          set -euo pipefail",
  '          [ "$HEAD_REPO" = "$GITHUB_REPOSITORY" ] || { echo \'Fork PRs are not supported\' >&2; exit 1; }',
  '          permission=$(gh api "repos/$GITHUB_REPOSITORY/collaborators/$LABEL_ACTOR/permission" --jq .permission)',
  "          case \"$permission\" in admin|write) ;; *) echo 'Label actor lacks write access' >&2; exit 1;; esac",
  '          [ -n "$RALPHWORKS_MODEL" ] || exit 1',
  "      - uses: actions/checkout@v4",
  "        with:",
  "          ref: ${{ github.event.pull_request.head.sha }}",
  "          persist-credentials: false",
  "          fetch-depth: 0",
  "      - uses: pnpm/action-setup@v4",
  "        with:",
  "          version: 10.13.1",
  "      - uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 24",
  "      - name: Prepare RalphWorks and review task",
  "        env:",
  "          SOURCE_TOKEN: ${{ secrets.RALPHWORKS_REPO_TOKEN }}",
  "        run: |",
  "          set -euo pipefail",
  ...RALPHWORKS_CHECKOUT_AND_BUILD,
  '          git fetch origin "$BASE_REF"',
  '          git diff --binary "origin/$BASE_REF...$HEAD_SHA" > "$RUNNER_TEMP/pr.diff"',
  "          cat > \"$RUNNER_TEMP/review-task.md\" <<'TASK'",
  "          Review the changes in the current pull request against the base branch. Read the diff at the path provided below and inspect relevant source files. Write a concise Markdown review to .ralph/review.md. Include concrete findings with file paths and line numbers, or state that no actionable findings were found. Do not modify tracked project files. Signal DONE once the report exists.",
  "          TASK",
  '          printf \'\\nDiff path: %s\\n\' "$RUNNER_TEMP/pr.diff" >> "$RUNNER_TEMP/review-task.md"',
  "          mkdir -p .ralph",
  "      - name: Run RalphWorks review",
  "        id: ralph",
  "        env:",
  ...PROVIDER_CREDENTIAL_ENV,
  "        run: |",
  "          set -euo pipefail",
  '          if [ -n "$RALPHWORKS_AUTH_SECRET_NAME" ]; then export "$RALPHWORKS_AUTH_SECRET_NAME=$RALPHWORKS_AUTH_SECRET_VALUE"; fi',
  '          node "$RUNNER_TEMP/ralphworks/dist/cli.js" run "$RUNNER_TEMP/review-task.md" --executor host --check \'test -s .ralph/review.md\' --max-iterations 2 --max-minutes 20 --max-cost-usd 1',
  "      - uses: actions/upload-artifact@v4",
  "        if: always() && steps.ralph.outcome != 'skipped'",
  "        with:",
  "          name: ralphworks-review",
  "          path: |",
  "            .ralph/review.md",
  "            .ralph/runs/",
  "          if-no-files-found: warn",
  "",
  "  publish:",
  "    needs: review",
  "    if: always() && github.event.label.name == 'ralphworks:review' && github.event.pull_request.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    permissions:",
  "      pull-requests: read",
  "      actions: read",
  "    env:",
  "      GH_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "      GH_REPO: ${{ github.repository }}",
  "      PR_NUMBER: ${{ github.event.pull_request.number }}",
  "      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
  "    steps:",
  "      - name: Require successful review",
  "        run: |",
  '          [ "${{ needs.review.result }}" = success ] || exit 1',
  '          [ -n "$GH_TOKEN" ] || exit 1',
  "      - uses: actions/download-artifact@v4",
  "        with:",
  "          name: ralphworks-review",
  "          path: ${{ runner.temp }}/review",
  "      - name: Publish review",
  "        run: |",
  "          set -euo pipefail",
  '          report="$RUNNER_TEMP/review/review.md"',
  '          [ -s "$report" ] || exit 1',
  '          current=$(gh pr view "$PR_NUMBER" --json headRefOid --jq .headRefOid)',
  "          [ \"$current\" = '${{ github.event.pull_request.head.sha }}' ] || { echo 'PR advanced during review' >&2; exit 1; }",
  '          printf \'\\n\\nRalphWorks review run: %s\\n\' "$RUN_URL" >> "$report"',
  '          gh api --method POST "repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" -f event=COMMENT -F body=@"$report" >/dev/null',
  '          gh pr ready "$PR_NUMBER" || true',
  "          gh pr edit \"$PR_NUMBER\" --remove-label 'ralphworks:review' || true",
  "      - name: Report failure",
  "        if: failure() && env.GH_TOKEN != ''",
  "        run: |",
  "          gh pr edit \"$PR_NUMBER\" --remove-label 'ralphworks:review' || true",
  "          gh pr edit \"$PR_NUMBER\" --add-label 'ralphworks:blocked' || true",
  '          gh pr comment "$PR_NUMBER" --body "RalphWorks review failed. Inspect $RUN_URL, then re-add the review label to retry."',
  "",
].join("\n");
