import { PROVIDER_CREDENTIAL_ENV, RALPHWORKS_CHECKOUT_AND_BUILD } from "./workflow-execution.ts";

export const PRD_IMPLEMENT_WORKFLOW = [
  "name: RalphWorks Implement PRD",
  "",
  "on:",
  "  issues:",
  "    types: [labeled]",
  "",
  "concurrency:",
  "  group: ralphworks-prd-implement-${{ github.event.issue.number }}",
  "  cancel-in-progress: false",
  "",
  "jobs:",
  "  implement:",
  "    if: github.event.label.name == 'ralphworks:implement-prd' && github.event.issue.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    timeout-minutes: 60",
  "    permissions:",
  "      contents: read",
  "      issues: read",
  "    outputs:",
  "      child: ${{ steps.select.outputs.child }}",
  "    env:",
  "      GH_TOKEN: ${{ github.token }}",
  "      GH_REPO: ${{ github.repository }}",
  "      PRD_NUMBER: ${{ github.event.issue.number }}",
  "      LABEL_ACTOR: ${{ github.event.sender.login }}",
  "      BRANCH: ralphworks/prd-${{ github.event.issue.number }}",
  "      RALPHWORKS_MODEL: ${{ vars.RALPHWORKS_MODEL }}",
  "      RALPHWORKS_CHECK: ${{ vars.RALPHWORKS_ISSUE_CHECK }}",
  "      RALPHWORKS_REF: ${{ vars.RALPHWORKS_REF || 'v0.2.0' }}",
  "      RALPHWORKS_SOURCE_REPO: ${{ vars.RALPHWORKS_SOURCE_REPO || 'OctopusGarage/ralphworks' }}",
  "    steps:",
  "      - name: Select next sub-issue",
  "        id: select",
  "        run: |",
  "          set -euo pipefail",
  '          permission=$(gh api "repos/$GITHUB_REPOSITORY/collaborators/$LABEL_ACTOR/permission" --jq .permission)',
  '          case "$permission" in admin|write) ;; *) exit 1;; esac',
  '          [ -n "$RALPHWORKS_MODEL" ] && [ -n "$RALPHWORKS_CHECK" ] || exit 1',
  '          children=$(gh api "repos/$GITHUB_REPOSITORY/issues/$PRD_NUMBER/sub_issues")',
  '          [ "$(jq length <<< "$children")" -gt 0 ] || { echo \'No sub-issues\' >&2; exit 1; }',
  '          child=$(jq -r \'[.[] | select(.state == "open") | .number] | first // empty\' <<< "$children")',
  "          [ -n \"$child\" ] || { echo 'All sub-issues are closed' >&2; exit 1; }",
  '          echo "child=$child" >> "$GITHUB_OUTPUT"',
  '          if gh api "repos/$GITHUB_REPOSITORY/branches/$BRANCH" --jq .name >/dev/null 2>&1; then',
  '            echo "ref=$BRANCH" >> "$GITHUB_OUTPUT"',
  "          else",
  '            echo "ref=${{ github.event.repository.default_branch }}" >> "$GITHUB_OUTPUT"',
  "          fi",
  "      - name: Mark PRD in progress",
  "        env:",
  "          ISSUE_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "        run: |",
  '          [ -n "$ISSUE_TOKEN" ] || exit 1',
  '          GH_TOKEN="$ISSUE_TOKEN" gh issue edit "$PRD_NUMBER" --remove-label \'ralphworks:implement-prd\' || true',
  '          GH_TOKEN="$ISSUE_TOKEN" gh issue edit "$PRD_NUMBER" --remove-label \'ralphworks:blocked\' || true',
  '          GH_TOKEN="$ISSUE_TOKEN" gh issue edit "$PRD_NUMBER" --add-label \'ralphworks:in-progress\'',
  "      - uses: actions/checkout@v4",
  "        with:",
  "          ref: ${{ steps.select.outputs.ref }}",
  "          persist-credentials: false",
  "          fetch-depth: 0",
  "      - uses: pnpm/action-setup@v4",
  "        with:",
  "          version: 10.13.1",
  "      - uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 24",
  "      - name: Prepare task and dependencies",
  "        env:",
  "          SOURCE_TOKEN: ${{ secrets.RALPHWORKS_REPO_TOKEN }}",
  "          CHILD_NUMBER: ${{ steps.select.outputs.child }}",
  "        run: |",
  "          set -euo pipefail",
  ...RALPHWORKS_CHECKOUT_AND_BUILD,
  "          if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile",
  "          elif [ -f package-lock.json ]; then npm ci",
  "          elif [ -f yarn.lock ]; then yarn install --frozen-lockfile",
  "          fi",
  '          gh api "repos/$GITHUB_REPOSITORY/issues/$PRD_NUMBER" --jq \'{title,body}\' > "$RUNNER_TEMP/parent.json"',
  '          gh api "repos/$GITHUB_REPOSITORY/issues/$CHILD_NUMBER" --jq \'{title,body}\' > "$RUNNER_TEMP/child.json"',
  "          cat > \"$RUNNER_TEMP/prd-task.md\" <<'TASK'",
  "          Implement the selected PRD sub-issue in this worktree. Read the parent and child issue JSON files below, follow the child's acceptance criteria, add meaningful tests, run the configured checks, and signal DONE. Do not commit or change Git HEAD. Work only on the selected child, preserving earlier work on this branch.",
  "          TASK",
  '          printf \'\\nParent: %s\\nChild: %s\\n\' "$RUNNER_TEMP/parent.json" "$RUNNER_TEMP/child.json" >> "$RUNNER_TEMP/prd-task.md"',
  '          echo "RALPH_BASE=$(git rev-parse HEAD)" >> "$GITHUB_ENV"',
  "      - name: Run RalphWorks",
  "        id: ralph",
  "        env:",
  ...PROVIDER_CREDENTIAL_ENV,
  "        run: |",
  "          set -euo pipefail",
  '          if [ -n "$RALPHWORKS_AUTH_SECRET_NAME" ]; then export "$RALPHWORKS_AUTH_SECRET_NAME=$RALPHWORKS_AUTH_SECRET_VALUE"; fi',
  '          node "$RUNNER_TEMP/ralphworks/dist/cli.js" run "$RUNNER_TEMP/prd-task.md" --executor host --check "$RALPHWORKS_CHECK" --max-iterations 5 --max-minutes 30 --max-cost-usd 3',
  "      - name: Export patch",
  "        if: always() && steps.ralph.outcome != 'skipped'",
  "        run: |",
  "          mkdir -p .ralph/export",
  "          git add -N --all",
  "          git diff --binary \"${RALPH_BASE:-HEAD}\" -- . ':!.ralph' > .ralph/export/change.patch",
  '          git rev-parse "${RALPH_BASE:-HEAD}" > .ralph/export/base-sha.txt',
  "      - uses: actions/upload-artifact@v4",
  "        if: always() && steps.ralph.outcome != 'skipped'",
  "        with:",
  "          name: ralphworks-prd-result",
  "          path: |",
  "            .ralph/export/",
  "            .ralph/runs/",
  "          if-no-files-found: warn",
  "",
  "  deliver:",
  "    needs: implement",
  "    if: always() && github.event.label.name == 'ralphworks:implement-prd' && github.event.issue.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    permissions:",
  "      contents: read",
  "      issues: read",
  "      pull-requests: read",
  "      actions: read",
  "    env:",
  "      GH_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "      GH_REPO: ${{ github.repository }}",
  "      PRD_NUMBER: ${{ github.event.issue.number }}",
  "      CHILD_NUMBER: ${{ needs.implement.outputs.child }}",
  "      BRANCH: ralphworks/prd-${{ github.event.issue.number }}",
  "      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
  "    steps:",
  "      - name: Require completed run and select branch",
  "        id: branch",
  "        run: |",
  "          set -euo pipefail",
  '          [ "${{ needs.implement.result }}" = success ] || exit 1',
  '          [ -n "$GH_TOKEN" ] && [ -n "$CHILD_NUMBER" ] || exit 1',
  '          if gh api "repos/$GITHUB_REPOSITORY/branches/$BRANCH" --jq .name >/dev/null 2>&1; then',
  '            echo "ref=$BRANCH" >> "$GITHUB_OUTPUT"',
  "          else",
  '            echo "ref=${{ github.event.repository.default_branch }}" >> "$GITHUB_OUTPUT"',
  "          fi",
  "      - uses: actions/download-artifact@v4",
  "        with:",
  "          name: ralphworks-prd-result",
  "          path: ${{ runner.temp }}/prd-result",
  "      - name: Validate result",
  "        run: |",
  "          set -euo pipefail",
  '          result=$(find "$RUNNER_TEMP/prd-result/runs" -name result.json -type f -print -quit)',
  '          [ -n "$result" ] || exit 1',
  '          jq -e \'.status == "completed" and (.iterations as $last | [.checks[] | select(.iteration == $last)] | length > 0) and (.iterations as $last | [.checks[] | select(.iteration == $last and .exitCode != 0)] | length == 0)\' "$result" >/dev/null',
  '          [ -s "$RUNNER_TEMP/prd-result/export/change.patch" ] || exit 1',
  "      - uses: actions/checkout@v4",
  "        with:",
  "          ref: ${{ steps.branch.outputs.ref }}",
  "          persist-credentials: false",
  "          fetch-depth: 0",
  "      - name: Apply patch and advance PRD",
  "        env:",
  "          PRD_TITLE: ${{ github.event.issue.title }}",
  "        run: |",
  "          set -euo pipefail",
  '          base=$(cat "$RUNNER_TEMP/prd-result/export/base-sha.txt")',
  '          [ "$(git rev-parse HEAD)" = "$base" ] || { echo \'PRD branch advanced\' >&2; exit 1; }',
  '          git switch -c "$BRANCH" 2>/dev/null || git switch "$BRANCH"',
  '          git apply --check "$RUNNER_TEMP/prd-result/export/change.patch"',
  '          git apply "$RUNNER_TEMP/prd-result/export/change.patch"',
  "          git config user.name 'ralphworks[bot]'",
  "          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'",
  "          git add -A",
  '          git commit -m "feat: implement PRD #$PRD_NUMBER sub-issue #$CHILD_NUMBER"',
  "          auth=$(printf 'x-access-token:%s' \"$GH_TOKEN\" | base64 | tr -d '\\n')",
  '          git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $auth" push origin "HEAD:refs/heads/$BRANCH"',
  "          pr=$(gh pr list --head \"$BRANCH\" --state open --json number --jq '.[0].number // empty')",
  '          if [ -z "$pr" ]; then',
  '            printf \'Closes #%s\\n\\nRalphWorks PRD implementation. Review all sub-issues and checks before merging.\\n\' "$PRD_NUMBER" > "$RUNNER_TEMP/pr-body.md"',
  "            title=\"PRD #$PRD_NUMBER: ${PRD_TITLE//$'\\n'/ }\"",
  '            url=$(gh pr create --draft --base \'${{ github.event.repository.default_branch }}\' --head "$BRANCH" --title "${title:0:256}" --body-file "$RUNNER_TEMP/pr-body.md")',
  "            pr=${url##*/}",
  "          fi",
  '          gh issue close "$CHILD_NUMBER" --comment "Implemented on PR #$pr in $(git rev-parse --short HEAD). Parent PRD #$PRD_NUMBER."',
  "          gh issue edit \"$PRD_NUMBER\" --remove-label 'ralphworks:in-progress' || true",
  '          remaining=$(gh api "repos/$GITHUB_REPOSITORY/issues/$PRD_NUMBER/sub_issues" --jq \'[.[] | select(.state == "open")] | length\')',
  '          if [ "$remaining" -gt 0 ]; then',
  '            gh issue comment "$PRD_NUMBER" --body "Completed sub-issue #$CHILD_NUMBER on PR #$pr. $remaining remain. Continuing in a new run. $RUN_URL"',
  "            gh issue edit \"$PRD_NUMBER\" --add-label 'ralphworks:implement-prd'",
  "          else",
  '            gh issue comment "$PRD_NUMBER" --body "All sub-issues implemented on draft PR #$pr. Review run: $RUN_URL"',
  "            gh pr edit \"$pr\" --add-label 'ralphworks:review'",
  "          fi",
  "      - name: Report failure",
  "        if: failure() && env.GH_TOKEN != ''",
  "        run: |",
  "          gh issue edit \"$PRD_NUMBER\" --remove-label 'ralphworks:in-progress' || true",
  "          gh issue edit \"$PRD_NUMBER\" --remove-label 'ralphworks:implement-prd' || true",
  "          gh issue edit \"$PRD_NUMBER\" --add-label 'ralphworks:blocked' || true",
  '          gh issue comment "$PRD_NUMBER" --body "RalphWorks PRD implementation failed at sub-issue #$CHILD_NUMBER. Inspect $RUN_URL before retrying."',
  "",
].join("\n");
