import { failureComment, PROVIDER_CREDENTIAL_ENV, RALPHWORKS_CHECKOUT_AND_BUILD } from "./workflow-execution.ts";

export const PRD_SPLIT_WORKFLOW = [
  "name: RalphWorks Split PRD",
  "",
  "on:",
  "  issues:",
  "    types: [labeled]",
  "",
  "concurrency:",
  "  group: ralphworks-prd-split-${{ github.event.issue.number }}",
  "  cancel-in-progress: false",
  "",
  "jobs:",
  "  split:",
  "    if: github.event.label.name == 'ralphworks:to-issues' && github.event.issue.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    timeout-minutes: 40",
  "    permissions:",
  "      contents: read",
  "      issues: read",
  "    env:",
  "      GH_TOKEN: ${{ github.token }}",
  "      GH_REPO: ${{ github.repository }}",
  "      ISSUE_NUMBER: ${{ github.event.issue.number }}",
  "      LABEL_ACTOR: ${{ github.event.sender.login }}",
  "      RALPHWORKS_MODEL: ${{ vars.RALPHWORKS_MODEL }}",
  "      RALPHWORKS_REF: ${{ vars.RALPHWORKS_REF || 'v0.2.0' }}",
  "      RALPHWORKS_SOURCE_REPO: ${{ vars.RALPHWORKS_SOURCE_REPO || 'OctopusGarage/ralphworks' }}",
  "    steps:",
  "      - name: Authorize and require empty PRD",
  "        run: |",
  "          set -euo pipefail",
  '          permission=$(gh api "repos/$GITHUB_REPOSITORY/collaborators/$LABEL_ACTOR/permission" --jq .permission)',
  '          case "$permission" in admin|write) ;; *) exit 1;; esac',
  '          [ -n "$RALPHWORKS_MODEL" ] || exit 1',
  '          count=$(gh api "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/sub_issues" --jq length)',
  "          [ \"$count\" = 0 ] || { echo 'PRD already has sub-issues; re-run the failed delivery job from the original run' >&2; exit 1; }",
  "      - uses: actions/checkout@v4",
  "        with:",
  "          persist-credentials: false",
  "      - uses: pnpm/action-setup@v4",
  "        with:",
  "          version: 10.13.1",
  "      - uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 24",
  "      - name: Prepare RalphWorks and PRD task",
  "        env:",
  "          SOURCE_TOKEN: ${{ secrets.RALPHWORKS_REPO_TOKEN }}",
  "          ISSUE_TITLE: ${{ github.event.issue.title }}",
  "          ISSUE_BODY: ${{ github.event.issue.body }}",
  "        run: |",
  "          set -euo pipefail",
  ...RALPHWORKS_CHECKOUT_AND_BUILD,
  "          mkdir -p .ralph",
  '          printf \'PRD #%s: %s\\n\\n%s\\n\' "$ISSUE_NUMBER" "$ISSUE_TITLE" "$ISSUE_BODY" > "$RUNNER_TEMP/prd.md"',
  "          cat > \"$RUNNER_TEMP/split-task.md\" <<'TASK'",
  '          Read the PRD at the path below and inspect the repository. Break it into 2 to 8 independently verifiable, ordered implementation tasks. Write .ralph/subissues.json as a JSON array of objects with nonempty "title" and "body" strings. Each body must contain concrete acceptance criteria. Do not change tracked project files. Signal DONE when the JSON file is valid.',
  "          TASK",
  '          printf \'\\nPRD path: %s\\n\' "$RUNNER_TEMP/prd.md" >> "$RUNNER_TEMP/split-task.md"',
  "      - name: Run RalphWorks",
  "        id: ralph",
  "        env:",
  ...PROVIDER_CREDENTIAL_ENV,
  "        run: |",
  "          set -euo pipefail",
  '          if [ -n "$RALPHWORKS_AUTH_SECRET_NAME" ]; then export "$RALPHWORKS_AUTH_SECRET_NAME=$RALPHWORKS_AUTH_SECRET_VALUE"; fi',
  '          node "$RUNNER_TEMP/ralphworks/dist/cli.js" run "$RUNNER_TEMP/split-task.md" --executor host --check \'jq -e "type == \\"array\\" and length >= 2 and length <= 8 and all(.[]; (.title | type == \\"string\\" and length > 0) and (.body | type == \\"string\\" and length > 0))" .ralph/subissues.json\' --max-iterations 3 --max-minutes 20 --max-cost-usd 1',
  "      - uses: actions/upload-artifact@v4",
  "        if: always() && steps.ralph.outcome != 'skipped'",
  "        with:",
  "          name: ralphworks-prd-split",
  "          path: |",
  "            .ralph/subissues.json",
  "            .ralph/runs/",
  "          if-no-files-found: warn",
  "",
  "  publish:",
  "    needs: split",
  "    if: always() && github.event.label.name == 'ralphworks:to-issues' && github.event.issue.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    permissions:",
  "      issues: read",
  "      actions: read",
  "    env:",
  "      GH_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "      GH_REPO: ${{ github.repository }}",
  "      ISSUE_NUMBER: ${{ github.event.issue.number }}",
  "      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
  "    steps:",
  "      - name: Require successful split",
  "        run: |",
  '          [ "${{ needs.split.result }}" = success ] || exit 1',
  '          [ -n "$GH_TOKEN" ] || exit 1',
  "      - uses: actions/download-artifact@v4",
  "        with:",
  "          name: ralphworks-prd-split",
  "          path: ${{ runner.temp }}/split",
  "      - name: Create sub-issues",
  "        run: |",
  "          set -euo pipefail",
  '          result=$(find "$RUNNER_TEMP/split/runs" -name result.json -type f -print -quit)',
  '          jq -e \'.status == "completed"\' "$result" >/dev/null',
  '          file="$RUNNER_TEMP/split/subissues.json"',
  '          jq -e \'type == "array" and length >= 2 and length <= 8 and all(.[]; (.title | type == "string" and length > 0) and (.body | type == "string" and length > 0))\' "$file" >/dev/null',
  '          children=$(gh api "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/sub_issues")',
  '          total=$(jq length "$file")',
  '          [ "$(jq length <<< "$children")" -le "$total" ] || { echo "PRD has more sub-issues than the proposal" >&2; exit 1; }',
  "          while IFS= read -r existing_marker; do",
  "            matched=false",
  "            for ((index = 1; index <= total; index++)); do",
  '              if [ "$existing_marker" = "<!-- ralphworks-prd-split:$GITHUB_RUN_ID:$index -->" ]; then matched=true; break; fi',
  "            done",
  '            [ "$matched" = true ] || { echo "PRD has a sub-issue outside this run; inspect it before retrying" >&2; exit 1; }',
  '          done < <(jq -r \'.[] | (.body // "") | split("\\n")[0]\' <<< "$children")',
  '          parent_id=$(gh api "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER" --jq .id)',
  "          index=0",
  "          jq -c '.[]' \"$file\" | while read -r item; do",
  "            index=$((index + 1))",
  '            title=$(jq -r .title <<< "$item")',
  '            body=$(jq -r .body <<< "$item")',
  '            marker="<!-- ralphworks-prd-split:$GITHUB_RUN_ID:$index -->"',
  '            body="$marker"$\'\\n\\n\'"$body"',
  '            existing=$(jq -c --arg marker "$marker" \'[.[] | select((.body // "") | startswith($marker))]\' <<< "$children")',
  '            [ "$(jq length <<< "$existing")" -le 1 ] || { echo "Duplicate sub-issue marker: $marker" >&2; exit 1; }',
  '            if [ "$(jq length <<< "$existing")" = 1 ]; then',
  '              jq -e --arg title "$title" --arg body "$body" \'.[0] | .title == $title and .body == $body\' <<< "$existing" >/dev/null || { echo "Existing sub-issue differs from proposal: $marker" >&2; exit 1; }',
  "              continue",
  "            fi",
  '            created=$(gh api --method POST "repos/$GITHUB_REPOSITORY/issues" -f title="$title" -f body="$body" -F parent_issue_id="$parent_id")',
  '            number=$(jq -r .number <<< "$created")',
  "            printf 'Created sub-issue #%s\\n' \"$number\"",
  "          done",
  "          gh issue edit \"$ISSUE_NUMBER\" --remove-label 'ralphworks:to-issues' || true",
  "          gh issue edit \"$ISSUE_NUMBER\" --remove-label 'ralphworks:blocked' || true",
  '          gh issue comment "$ISSUE_NUMBER" --body "RalphWorks created the ordered sub-issues. Review them, then add \\`ralphworks:implement-prd\\` to implement them. Run: $RUN_URL"',
  "      - name: Report failure",
  "        if: failure() && env.GH_TOKEN != ''",
  "        run: |",
  "          gh issue edit \"$ISSUE_NUMBER\" --remove-label 'ralphworks:to-issues' || true",
  "          gh issue edit \"$ISSUE_NUMBER\" --add-label 'ralphworks:blocked' || true",
  ...failureComment(
    "ralphworks-prd-split",
    "ISSUE_NUMBER",
    "ralphworks:to-issues",
    "RalphWorks PRD split failed. Inspect partial sub-issues; if only delivery failed, rerun the failed job from this run.",
  ),
  "",
].join("\n");
