export const QUEUE_WORKFLOW = [
  "name: RalphWorks Promote Queued",
  "",
  "on:",
  "  issues:",
  "    types: [closed]",
  "  workflow_dispatch:",
  "",
  "jobs:",
  "  promote:",
  "    runs-on: ubuntu-latest",
  "    permissions:",
  "      issues: read",
  "    env:",
  "      GH_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "      GH_REPO: ${{ github.repository }}",
  "    steps:",
  "      - name: Promote unblocked queued issues",
  "        run: |",
  "          set -euo pipefail",
  '          [ -n "$GH_TOKEN" ] || exit 1',
  "          gh issue list --state open --label 'ralphworks:queued' --limit 100 --json number --jq '.[].number' | while read -r issue; do",
  '            [ -n "$issue" ] || continue',
  '            blocked=$(gh api "repos/$GITHUB_REPOSITORY/issues/$issue/dependencies/blocked_by" --jq \'[.[] | select(.state == "open")] | length\')',
  '            [ "$blocked" = 0 ] || continue',
  '            children=$(gh api "repos/$GITHUB_REPOSITORY/issues/$issue/sub_issues" --jq length)',
  "            gh issue edit \"$issue\" --remove-label 'ralphworks:queued'",
  '            if [ "$children" -gt 0 ]; then',
  "              gh issue edit \"$issue\" --add-label 'ralphworks:implement-prd'",
  "            else",
  "              gh issue edit \"$issue\" --add-label 'ralphworks:run'",
  "            fi",
  "            gh issue comment \"$issue\" --body 'Dependencies are closed; RalphWorks started implementation.'",
  "          done",
  "",
].join("\n");
