import { PROVIDER_CREDENTIAL_ENV, RALPHWORKS_CHECKOUT_AND_BUILD } from "./workflow-execution.ts";

export const UPDATE_BRANCH_WORKFLOW = [
  "name: RalphWorks Update Branch",
  "",
  "on:",
  "  pull_request_target:",
  "    types: [labeled]",
  "",
  "concurrency:",
  "  group: ralphworks-update-${{ github.event.pull_request.number }}",
  "  cancel-in-progress: false",
  "",
  "jobs:",
  "  update:",
  "    if: github.event.label.name == 'ralphworks:update-branch' && github.event.pull_request.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    timeout-minutes: 60",
  "    permissions:",
  "      contents: read",
  "      pull-requests: read",
  "    env:",
  "      GH_TOKEN: ${{ github.token }}",
  "      GH_REPO: ${{ github.repository }}",
  "      PR_NUMBER: ${{ github.event.pull_request.number }}",
  "      LABEL_ACTOR: ${{ github.event.sender.login }}",
  "      HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}",
  "      HEAD_SHA: ${{ github.event.pull_request.head.sha }}",
  "      BASE_REF: ${{ github.event.pull_request.base.ref }}",
  "      RALPHWORKS_MODEL: ${{ vars.RALPHWORKS_MODEL }}",
  "      RALPHWORKS_CHECK: ${{ vars.RALPHWORKS_ISSUE_CHECK }}",
  "      RALPHWORKS_REF: ${{ vars.RALPHWORKS_REF || 'v0.1.1' }}",
  "      RALPHWORKS_SOURCE_REPO: ${{ vars.RALPHWORKS_SOURCE_REPO || 'OctopusGarage/ralphworks' }}",
  "    steps:",
  "      - name: Authorize branch update",
  "        run: |",
  "          set -euo pipefail",
  '          [ "$HEAD_REPO" = "$GITHUB_REPOSITORY" ] || { echo \'Fork PRs are not supported\' >&2; exit 1; }',
  '          permission=$(gh api "repos/$GITHUB_REPOSITORY/collaborators/$LABEL_ACTOR/permission" --jq .permission)',
  "          case \"$permission\" in admin|write) ;; *) echo 'Label actor lacks write access' >&2; exit 1;; esac",
  '          [ -n "$RALPHWORKS_CHECK" ] || exit 1',
  "      - uses: actions/checkout@v4",
  "        with:",
  "          ref: ${{ github.event.pull_request.head.sha }}",
  "          persist-credentials: false",
  "          fetch-depth: 0",
  "      - uses: pnpm/action-setup@v4",
  "        with:",
  "          version: 10.13.1",
  "      - uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 24",
  "      - name: Prepare merge and dependencies",
  "        id: merge",
  "        run: |",
  "          set -euo pipefail",
  '          git fetch origin "$BASE_REF"',
  '          base=$(git rev-parse "origin/$BASE_REF")',
  "          mkdir -p .ralph/export",
  "          printf '%s\\n' \"$base\" > .ralph/export/base-sha.txt",
  "          printf '%s\\n' \"$HEAD_SHA\" > .ralph/export/head-sha.txt",
  '          if git merge-base --is-ancestor "$base" "$HEAD_SHA"; then',
  "            echo 'up_to_date=true' >> \"$GITHUB_OUTPUT\"",
  "            exit 0",
  "          fi",
  "          echo 'up_to_date=false' >> \"$GITHUB_OUTPUT\"",
  "          git config user.name 'ralphworks[bot]'",
  "          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'",
  '          git merge --no-commit --no-ff "$base" || true',
  '          if [ -n "$(git diff --name-only --diff-filter=U)" ]; then echo "conflicts=true" >> "$GITHUB_OUTPUT"',
  '          else echo "conflicts=false" >> "$GITHUB_OUTPUT"; fi',
  "          if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile",
  "          elif [ -f package-lock.json ]; then npm ci",
  "          elif [ -f yarn.lock ]; then yarn install --frozen-lockfile",
  "          fi",
  "          cat > \"$RUNNER_TEMP/check-merge.sh\" <<'SCRIPT'",
  "          #!/usr/bin/env bash",
  "          set -euo pipefail",
  '          [ -z "$(git diff --name-only --diff-filter=U)" ]',
  '          bash -lc "$RALPHWORKS_CHECK"',
  "          SCRIPT",
  '          chmod +x "$RUNNER_TEMP/check-merge.sh"',
  "      - name: Prepare RalphWorks for conflicts",
  "        if: steps.merge.outputs.conflicts == 'true'",
  "        env:",
  "          SOURCE_TOKEN: ${{ secrets.RALPHWORKS_REPO_TOKEN }}",
  "        run: |",
  "          set -euo pipefail",
  ...RALPHWORKS_CHECKOUT_AND_BUILD,
  "      - name: Resolve conflicts with RalphWorks",
  "        if: steps.merge.outputs.conflicts == 'true'",
  "        id: ralph",
  "        env:",
  ...PROVIDER_CREDENTIAL_ENV,
  "        run: |",
  "          set -euo pipefail",
  '          if [ -n "$RALPHWORKS_AUTH_SECRET_NAME" ]; then export "$RALPHWORKS_AUTH_SECRET_NAME=$RALPHWORKS_AUTH_SECRET_VALUE"; fi',
  '          if [ -z "$(git diff --name-only --diff-filter=U)" ]; then exit 0; fi',
  '          [ -n "$RALPHWORKS_MODEL" ] || exit 1',
  "          printf 'Resolve the current Git merge conflicts, preserve the intended changes from both branches, run the configured checks, and signal DONE. Do not commit or change HEAD.\\n' > \"$RUNNER_TEMP/update-task.md\"",
  '          node "$RUNNER_TEMP/ralphworks/dist/cli.js" run "$RUNNER_TEMP/update-task.md" --executor host --check "bash $RUNNER_TEMP/check-merge.sh" --max-iterations 5 --max-minutes 30 --max-cost-usd 3',
  "      - name: Validate and export merged tree",
  "        if: steps.merge.outputs.up_to_date == 'false'",
  "        run: |",
  "          set -euo pipefail",
  '          bash "$RUNNER_TEMP/check-merge.sh"',
  "          git add -A",
  "          git diff --binary \"$HEAD_SHA\" -- . ':!.ralph' > .ralph/export/change.patch",
  "          [ -s .ralph/export/change.patch ] || { echo 'Merge produced no changes' >&2; exit 1; }",
  "      - uses: actions/upload-artifact@v4",
  "        if: always() && steps.merge.outcome != 'skipped'",
  "        with:",
  "          name: ralphworks-update",
  "          path: |",
  "            .ralph/export/",
  "            .ralph/runs/",
  "          if-no-files-found: warn",
  "",
  "  deliver:",
  "    needs: update",
  "    if: always() && github.event.label.name == 'ralphworks:update-branch' && github.event.pull_request.state == 'open'",
  "    runs-on: ubuntu-latest",
  "    permissions:",
  "      contents: read",
  "      pull-requests: read",
  "      actions: read",
  "    env:",
  "      GH_TOKEN: ${{ secrets.RALPHWORKS_ISSUE_TOKEN }}",
  "      GH_REPO: ${{ github.repository }}",
  "      PR_NUMBER: ${{ github.event.pull_request.number }}",
  "      BRANCH: ${{ github.event.pull_request.head.ref }}",
  "      BASE_REF: ${{ github.event.pull_request.base.ref }}",
  "      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
  "    steps:",
  "      - name: Require successful update",
  "        run: |",
  '          [ "${{ needs.update.result }}" = success ] || exit 1',
  '          [ -n "$GH_TOKEN" ] || exit 1',
  "      - uses: actions/download-artifact@v4",
  "        with:",
  "          name: ralphworks-update",
  "          path: ${{ runner.temp }}/update",
  "      - uses: actions/checkout@v4",
  "        with:",
  "          ref: ${{ github.event.pull_request.head.sha }}",
  "          persist-credentials: false",
  "          fetch-depth: 0",
  "      - name: Publish merge commit or up-to-date result",
  "        run: |",
  "          set -euo pipefail",
  '          head=$(cat "$RUNNER_TEMP/update/export/head-sha.txt")',
  '          base=$(cat "$RUNNER_TEMP/update/export/base-sha.txt")',
  '          current=$(gh pr view "$PR_NUMBER" --json headRefOid --jq .headRefOid)',
  '          current_base=$(gh api "repos/$GITHUB_REPOSITORY/git/ref/heads/$BASE_REF" --jq .object.sha)',
  '          if [ "$head" != "$current" ] || [ "$base" != "$current_base" ]; then echo \'PR or base branch advanced\' >&2; exit 1; fi',
  '          patch="$RUNNER_TEMP/update/export/change.patch"',
  '          if [ ! -s "$patch" ]; then',
  '            gh pr comment "$PR_NUMBER" --body "Branch already contains the current base. Run: $RUN_URL"',
  "            gh pr edit \"$PR_NUMBER\" --remove-label 'ralphworks:update-branch' || true",
  "            exit 0",
  "          fi",
  '          git apply --index --check "$patch"',
  '          git apply --index "$patch"',
  "          git config user.name 'ralphworks[bot]'",
  "          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'",
  "          tree=$(git write-tree)",
  '          commit=$(printf \'Merge %s into %s\\n\' "$BASE_REF" "$BRANCH" | git commit-tree "$tree" -p "$head" -p "$base")',
  "          auth=$(printf 'x-access-token:%s' \"$GH_TOKEN\" | base64 | tr -d '\\n')",
  '          git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $auth" push --force-with-lease="refs/heads/$BRANCH:$head" origin "$commit:refs/heads/$BRANCH"',
  '          gh pr comment "$PR_NUMBER" --body "RalphWorks updated the branch with merge commit $commit. Run: $RUN_URL"',
  "          gh pr edit \"$PR_NUMBER\" --remove-label 'ralphworks:update-branch' || true",
  "      - name: Report failure",
  "        if: failure() && env.GH_TOKEN != ''",
  "        run: |",
  "          gh pr edit \"$PR_NUMBER\" --remove-label 'ralphworks:update-branch' || true",
  "          gh pr edit \"$PR_NUMBER\" --add-label 'ralphworks:blocked' || true",
  '          gh pr comment "$PR_NUMBER" --body "RalphWorks branch update failed. Inspect $RUN_URL, then re-add the update-branch label to retry."',
  "",
].join("\n");
